//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2 {
	
	
	public partial class FormDataPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox firstName;
		
		protected System.Web.UI.WebControls.TextBox lastName;
		
		protected System.Web.UI.WebControls.Button ButtonSubmit;
		
		protected System.Web.UI.WebControls.TextBox DisplayData;
	}
}
